apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: e2e-fbc-strategy
  namespace: managed-release-team-tenant
spec:
  bundle: 'quay.io/scoheb/pipeline-fbc-release:debug-ir'
  params:
    - name: fromIndex
      value: 'quay.io/scoheb/fbc-index-testing:latest'
    - name: targetIndex
      value: 'quay.io/scoheb/fbc-target-index-testing:latest'
    - name: binaryImage
      value: 'registry.redhat.io/openshift4/ose-operator-registry:v4.12'
    - name: requestUpdateTimeout
      value: '420'
    - name: buildTimeoutSeconds
      value: '480'
  pipeline: fbc-release
  policy: fbc-policy
  serviceAccount: release-service-account