apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: e2e-fbc-strategy
  namespace: managed-release-team-tenant
spec:
  params:
    - name: fromIndex
      value: 'quay.io/scoheb/fbc-index-testing:latest'
    - name: targetIndex
      value: 'quay.io/scoheb/fbc-target-index-testing:latest'
    - name: binaryImage
      value: 'registry.redhat.io/openshift4/ose-operator-registry:v4.12'
    - name: requestUpdateTimeout
      value: '420'
    - name: buildTimeoutSeconds
      value: '480'
  pipelineRef:
    params:
      - name: url
        value: https://github.com/scoheb/release-service-catalog.git
      - name: revision
        value: poc-signing
      - name: pathInRepo
        value: pipelines/fbc-force-signing-release/fbc-release.yaml
    resolver: "git"
  policy: fbc-policy
  serviceAccount: release-service-account
